### ISSUE TITLE
[Documentation] HTML for links seems to be escaped on several pages

### ISSUE THREAD

**Issue by rtournoy** [coar-notify/notify-protocol#8]
hello

on this page https://notify.coar-repositories.org/patterns/request-endorsement/

the HTML for the link seems to be escaped for `Pattern Categories:	<a href='/pattern-categories/requests'>Requests</a>`

it also happens on this page:
https://notify.coar-repositories.org/scenarios/3/

for `See these use-cases to understand this scenario in context: <a href="/use-cases/peer-review/">Peer-review</a>, <a href="/use-cases/endorsement/">Endorsement</a>, <a href="/use-cases/dissemination/">Dissemination</a>`

thanks

**Comment by paulwalk** [comment]
I have fixed these now - thanks for reporting!
